from setuptools import setup, find_packages

setup(
    name='yolov9',
    version='0.1.0',
    author='Sigal, Ignacio',
    author_email='ignacio@citricsheep.com',
    description='A YOLOv9 model fork adapted for custom use',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/citric-nacho/yolov9',
    packages=find_packages(),
    install_requires=[
        'gitpython',
        'ipython',
        'matplotlib>=3.2.2',
        'numpy>=1.18.5',
        'opencv-python>=4.1.1',
        'Pillow>=7.1.2',
        'psutil',
        'PyYAML>=5.3.1',
        'requests>=2.23.0',
        'scipy>=1.4.1',
        'thop>=0.1.1',
        'torch>=1.7.0',
        'torchvision>=0.8.1',
        'tqdm>=4.64.0',
        'tensorboard>=2.4.1',
        'pandas>=1.1.4',
        'seaborn>=0.11.0',
        'albumentations>=1.0.3',
        'pycocotools>=2.0'
    ],
    classifiers=[
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: GPL License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ],
    python_requires='>=3.6',
    include_package_data=True,
    keywords='yolo yolov9 object detection',
    license='GPL-3.0',
)